# Generated by Django 4.0.6 on 2022-09-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix_Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflixmodel',
            name='Poster_Movie_Categories',
            field=models.CharField(blank=True, choices=[('', '----- Select Option -----'), ('Action', 'Action'), ('Horror', 'Horror'), ('Drama', 'Drama'), ('Sci-fi', 'Sci-fi')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='netflixmodel',
            name='Poster_Movie_Hours',
            field=models.TimeField(blank=True, max_length=100, null=True),
        ),
    ]
