# Generated by Django 4.0.5 on 2023-02-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix_Admin', '0003_remove_netflixmodel_background_logo_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetflixModel',
        ),
    ]
