# Generated by Django 4.0.6 on 2022-07-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetflixModel',
            fields=[
                ('Background_Mini_Image', models.ImageField(upload_to='')),
                ('Background_Logo_Image', models.ImageField(upload_to='')),
                ('Background_Main_Image', models.ImageField(upload_to='')),
                ('User_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Poster_Movie_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Poster_Movie_Rank', models.CharField(blank=True, max_length=100, null=True)),
                ('Poster_Movie_Year', models.DateField()),
                ('Poster_Movie_Hours', models.CharField(blank=True, max_length=100, null=True)),
                ('Poster_Movie_Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Movie_Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Poster_Movie_Starring', models.CharField(blank=True, max_length=100, null=True)),
                ('Poster_Movie_Categories', models.CharField(blank=True, max_length=100, null=True)),
                ('Movie_Genres', models.CharField(blank=True, max_length=100, null=True)),
                ('Movie_Maker_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Movie_Audio', models.CharField(blank=True, max_length=100, null=True)),
                ('Movie_Subtitles', models.CharField(blank=True, max_length=100, null=True)),
                ('Movie_Cast', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
