# Generated by Django 4.0.5 on 2022-08-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix_User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetflixModel',
        ),
    ]
